# Generated by Django 6.0.1 on 2026-02-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('buyer', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.URLField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('cpv_codes', models.JSONField(blank=True, null=True)),
                ('procedure_type', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'À traiter'), ('doing', 'En cours'), ('submitted', 'Soumis'), ('won', 'Gagné'), ('lost', 'Perdu')], default='todo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.URLField()),
                ('kind', models.CharField(max_length=50)),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('storage_path', models.CharField(blank=True, max_length=500, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender')),
            ],
        ),
    ]
